### ISSUE TITLE
Embedded video

### ISSUE THREAD

**Issue by DutchPete** [kinmury/Golden-Book#8] opened 2021-10-29 11:04 UTC
I have the CodeMirror Options plug-in, and in Edit mode it renders the video correctly.

![image](https://user-images.githubusercontent.com/10794265/139423994-a7d0686c-b56a-443f-bf31-31103e1d3590.png)

But in Preview it does not:

![image](https://user-images.githubusercontent.com/10794265/139424041-020ed315-1a30-497e-ad59-b441c85bbbd7.png)

**Comment by DutchPete** [comment] 2021-10-30 02:34
The size is not the problem because in other themes it fits fine.

**Comment by kinmury** [comment] 2021-10-30 10:04
I can't fix the problem if I can't replicate it on my Vault. Could you please give me the code you used or some similar code that makes the same problem, so I can see it and then fix it. 

Just to make sure, aside of "CodeMirror" plugin, is there another plugin that is active and plays a role into making that issue?

**Comment by DutchPete** [comment] 2021-10-30 11:13
The code:
`<div class\="videoWrapper"\> <iframe width\="560" height\="315" src\="<iframe width="640" height="360" src="https://www.corbettreport.com/?powerpress_embed=36513-podcast&amp;powerpress_player=mediaelement-video" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>`

In other themes I have the same plug-in or even more and there is no interference.

**Comment by kinmury** [comment] 2021-10-30 12:11
Ehm... yup. I found the problem. If you read your code, you have a `iframe` withing another `iframe`. Is it wrong? No, it works just fine. But not with my theme.

I use from time to time `iframe`s, so I added format to that specific HTML variable. What happends with your code? Since you have 2 `iframe`s, my CSS formats both of the iframe's at the same time, giving you that result.

I actually picket ITS theme, just to see what happends and it work just fine. Reading the code, I found why it works with other themes, and its because most of them either don't give any format to the `iframe` variable or just make little adjustements that dont affect visually that variable.

If you use this code, it should work just fine:

```md
<div class="videoWrapper"\> 
  <iframe 
    width="560"
    height="315"
    src="https://www.corbettreport.com/?powerpress_embed=36513-podcast&amp;powerpress_player=mediaelement-video" 
    frameborder="0" 
    scrolling="no" 
    webkitAllowFullScreen 
    mozallowfullscreen 
    allowFullScreen>
  </iframe>
</div>
```

**Comment by DutchPete** [comment] 2021-10-30 12:20
Thanks for all that work. So, if I use Golden Book and want to embed a video, I should use this format and just change the `src` (source) line: correct?

**Comment by kinmury** [comment] 2021-10-30 12:27
I mean, yeah? Your code is work fine, the only problem is that you put an `iframe` inside another one, something that isn't needed, since one `iframe` can do all the work by itself.

And it's not just in this theme, but anywhere. The code is HTML, and as such, it's has his own laws, properties and characteristics. The best think to do is to code the HTML correctly and, if needed, use reference.

Since the issue is solved, I'm closing it.

Thank you for your contribution :D

**Closed by kinmury** 2021-10-30 12:27 UTC
